- type: entity
  id: StalkerRail
  name: rails #comment to make the bitch work
  description: Old railway tracks, the sleepers of which have already rotted and the metal has rusted.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Appearance
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/rails.rsi
    drawdepth: FloorTiles
    layers:
      - state: rail
        scale: 0.6, 0.6
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: FootstepModifier
    footstepSoundCollection:
      collection: FootstepCatwalk
      params:
        volume: 8

# ВАГОНЫ С ЦИСТЕРНАМИ

- type: entity
  id: StalkerCargoTank
  parent: BaseStructure
  name: Tank car
  description: A type of rolling stock for transporting liquids, including oil and its refined products, chemically active and aggressive liquid substances.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: cargo_tank
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargoTank1
  parent: BaseStructure
  name: Tank car
  description: A type of rolling stock for transporting liquids, including oil and its refined products, chemically active and aggressive liquid substances.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: cargo_tank1
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

# ТЕПЛОВОЗЫ

- type: entity
  id: StalkerPassHead
  parent: BaseStructure
  name: Diesel locomotive M62
  description: Soviet mainline six-axle diesel locomotive, originally designed for use in the CMEA countries. Produced by the Lugansk Diesel Locomotive Plant since 1965.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: passenger_head
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargoHead
  parent: BaseStructure
  name: Diesel locomotive TEM6-001
  description: Soviet six-axle shunting diesel locomotive, manufactured by the Bryansk plant. It was created as a universal locomotive, which after replacing the bogies or wheel pairs could operate on railways with a track width of 1000, 1067, 1435 and 1520 mm, and in both moderate and tropical climates.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: head_cargo
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargoHead1
  parent: BaseStructure
  name: Diesel locomotive M62
  description: Soviet mainline six-axle diesel locomotive, originally designed for use in the CMEA countries. Produced by the Lugansk Diesel Locomotive Plant since 1965.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: сargo_head
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargoHead2
  parent: BaseStructure
  name: Diesel locomotive TEM6-001
  description: Soviet six-axle shunting diesel locomotive, manufactured by the Bryansk plant. It was created as a universal locomotive, which after replacing the bogies or wheel pairs could operate on railways with a track width of 1000, 1067, 1435 and 1520 mm, and in both moderate and tropical climates.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: сargo_head2
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

# ПАССАЖИРСКИЕ ВАГОНЫ

- type: entity
  id: StalkerPassTrain
  parent: BaseStructure
  name: passenger carriage
  description: A unit of rolling stock designed to transport passengers.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: passenger_train
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerPassTrain1
  parent: BaseStructure
  name: passenger carriage
  description: A unit of rolling stock designed to transport passengers.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: passenger_train1
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerPassTrain2
  parent: BaseStructure
  name: passenger carriage
  description: A unit of rolling stock designed to transport passengers.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: passenger_train3
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

# ГРУЗОВЫЕ ВАГОНЫ

- type: entity
  id: StalkerCargo
  parent: BaseStructure
  name: freight car
  description: It is a railway vehicle without an engine, which was used for transporting goods.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: сargo
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargo1
  parent: BaseStructure
  name: freight car
  description: It is a railway vehicle without an engine, which was used for transporting goods.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: сargo1
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargo2
  parent: BaseStructure
  name: freight car
  description: It is a railway vehicle without an engine, which was used for transporting goods.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: сargo2
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargo3
  parent: BaseStructure
  name: freight car
  description: It is a railway vehicle without an engine, which was used for transporting goods.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: сargo3
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargo4
  parent: BaseStructure
  name: freight car
  description: It is a railway vehicle without an engine, which was used for transporting goods.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: сargo4
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargo5
  parent: BaseStructure
  name: freight car
  description: It is a railway vehicle without an engine, which was used for transporting goods.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: сargo5
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargo6
  parent: BaseStructure
  name: freight car
  description: It is a railway vehicle without an engine, which was used for transporting goods.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: сargo6
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargo7
  parent: BaseStructure
  name: freight car
  description: It is a railway vehicle without an engine, which was used for transporting goods.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: сargo7
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

