### PROJECT ###


- type: entity
  parent: ClothingHeadsetGrey
  id: ClothingHeadsetProject
  name: A.A.A.
  description: Algorithm is active, it is impossible to disable the Algorithm, obey the Algorithm.
  components:
    - type: ContainerContainer
      containers:
        key_slots: !type:Container
    - type: ContainerFill
      containers:
        key_slots:
        - EncryptionKeyPROJECT
    - type: Headset
    - type: EncryptionKeyHolder
      keySlots: 1
    - type: Sprite
      sprite: _Stalker/Groups/Project/code_project_garniture.rsi
    - type: Item
      size: Small
    - type: Clothing
      sprite: _Stalker/Groups/Project/code_project_garniture.rsi
      slots:
      - ears
    - type: Unremoveable
    - type: Armor
      armorClass: 0
      modifiers:
        flatReductions:
          Psy: 5

- type: entity
  parent: BaseItem
  id: EncryptionKeyPROJECT
  name: A.A.A. chip
  description: Algorithm is not active, re-enabling of Algorithm is impossible, do not obey the Algorithm.
  components:
  - type: EncryptionKey
    channels:
    - Project
    - Project1
    - Project2
    - Project3
    defaultChannel: Project
  - type: Sprite
    sprite: _Stalker/Groups/Project/crypt_project.rsi
    state: icon

- type: radioChannel
  id: Project3
  name: Threat Identification
  keycode: '4'
  frequency: 56573
  color: "#ff0000"
  longRange: true

- type: radioChannel
  id: Project2
  name: Identification of the Unwanted
  keycode: '5'
  frequency: 75923
  color: "#ffff00"
  longRange: true

- type: radioChannel
  id: Project1
  name: Identification of the Greens
  keycode: '6'
  frequency: 25858
  color: "#04ff00"
  longRange: true

- type: radioChannel
  id: Project
  name: Common Project
  keycode: '7'
  frequency: 94384
  color: "#00e1d7"
  longRange: true

- type: entity
  parent: IDCardStandard
  id: PROJECTIDCard
  name: Algorithm key card
  description: The algorithm is eternal!
  components:
  - type: Sprite
    sprite: _Stalker/Objects/Misc/id_cards.rsi
    layers:
    - state: project
  - type: Access
    tags:
    - Project

- type: entity
  parent: BaseItem
  id: ProjectPDA
  name: PDA ???
  description: Error Screen, this PDA would not work.
  components:
  - type: Trash
    time: 600
  - type: Unremoveable
  - type: Appearance
  - type: Sprite
    sprite: _Stalker/Objects/Devices/pda.rsi
    layers:
    - map: [ "enum.PdaVisualLayers.Base" ]
    - state: "light_overlay"
      map: [ "enum.PdaVisualLayers.Flashlight" ]
      shader: "unshaded"
      visible: false
    - state: "id_overlay"
      map: [ "enum.PdaVisualLayers.IdLight" ]
      shader: "unshaded"
      visible: false
  - type: Icon
    sprite: _Stalker/Objects/Devices/pda.rsi
    state: stalker_off
  - type: Pda
    id: PROJECTIDCard
    state: project_death
    paiSlot:
      priority: -2
      whitelist:
        components:
          - PAI
    penSlot:
      priority: -1
      whitelist:
        tags:
          - Write
    idSlot:
      name: ключ-карта Алгоритма
      ejectSound: /Audio/Machines/id_swipe.ogg
      insertSound: /Audio/Machines/id_insert.ogg
      whitelist:
        components:
          - IdCard
  - type: Item
    size: Small
  - type: Clothing
    quickEquip: false
    slots:
    - idcard
    - Belt

- type: entity
  parent: ClothingShoesMilitaryBase
  id: ClothingShoesBootsProject
  name: project hobnailed boots
  description: The Algorithm will not die, The Algorithm is eternal, The Algorithm is not afraid of anything!
  components:
  - type: Sprite
    sprite: Corvax/Clothing/Shoes/Boots/jackboots_project.rsi
  - type: Clothing
    sprite: Corvax/Clothing/Shoes/Boots/jackboots_project.rsi
  - type: FootstepModifier
    footstepSoundCollection:
      collection: FootstepBoots

- type: entity
  parent: ClothingBeltStorageBase
  id: ClothingBeltHolsterProject
  name: shoulder holster project
  description: Holster for carrying a pistol and ammunition.
  components:
  - type: Sprite
    sprite: _Stalker/Clothing/Belts/holster_project.rsi
  - type: Clothing
    sprite: _Stalker/Clothing/Belts/holster_project.rsi
  - type: Storage
    grid:
    - 0,0,3,1

- type: entity
  parent: ClothingEyesBase
  id: ClothingEyesHudProject
  name: project visor
  description: Looking into it, you see the entire algorithm that you follow..., but it only works if you have the same chip built into your head.
  components:
  - type: Sprite
    sprite: _Stalker/Clothing/Goggles/project_hud.rsi
  - type: Clothing
    sprite: _Stalker/Clothing/Goggles/project_hud.rsi
