- type: entity
  id: STBaseNPC
  suffix: ST, НІП
  abstract: true
  components:
    - type: Clickable
    - type: InteractionOutline
    - type: Sprite
      state: icon
    - type: Fixtures
      fixtures:
        fix1:
          shape:
            !type:PhysShapeCircle
            radius: 0.45
          mask:
            - FullTileMask
          layer:
            - GlassLayer
    - type: Speech
      speechVerb: Default
