- type: entity
  parent: STBaseWeapon
  id: STBaseWeaponGun
  name: A gun
  abstract: true
  components:
    # Дозволяє гарматам отримувати ефекти від модулів,
    # без цього ви можете додавати модулі, але ефекту не буде.
    - type: STWeaponModuleContainer
    - type: STWeight
      self: 2.7
    - type: Clothing
      equipDelay: 1
      slots:
        - Back
        - SuitStorage
      quickEquip: false
    - type: AmmoCounter
    - type: Item
      size: Large
      shape:
        - 0,0,5,1
    - type: Sprite
      layers:
        - state: base
          map: ["enum.GunVisualLayers.Base"]
        - state: mag-0
          map: ["enum.GunVisualLayers.Mag"]
    # - тип: CameraMagazineAmmoProvider
    - type: ItemSlots
      # Якщо ти зміниш калібр,
      # вам потрібно повністю переписати кожну властивість, описану тут
      slots:
        gun_magazine:
          name: Магазин
          priority: 3
        # Тут ви маєте налаштувати ваші модулі вундервафель,
        # ти можеш покласти їх на гармату спочатку через startingItem,
        # але пам'ятайте, якщо ви змінюєте контейнери,
        # вам доведеться перевказати їх усі заново.
        gun_chamber:
          name: Патронник
          priority: 1
    - type: ContainerContainer
      containers:
        gun_magazine: !type:ContainerSlot
        gun_chamber: !type:ContainerSlot
      muzzleState: muzzle
    - type: Appearance
    - type: PullDoAfter
      pullTime: 2.5
    - type: Craftable
    - type: RepositoryItem
      categoryName: Зброя
