- type: job
  id: EvolverPackFang
  name: Ікло зграї
  icon: pack
  description: Лютий воїн зграї, що уособлює її дику силу та первісні інстинкти.
  playTimeTracker: JobEvolverPackFang
  requirements:
    - !type:RoleTimeRequirement
      role: JobEvolverPackFang
      time: 1
    - !type:SpeciesRequirement
      species:
      - Moth
      - Diona
      - Arachnid
      - Reptilian
      - SlimePerson
      - Vox
  startingGear: STEvolverPackFangGear
  supervisors: Захищати зграю і розширювати її територію, діючи в перших рядах атак.
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Pack
            - Evolver
        - type: Bands
          band: Evolver
          bandIcon: pack
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: STEvolverPackFangGear
  equipment:
    id: BandPDA
    belt: ClothingBeltStorageWaistbag
    torso: STClothingTorsoJacketGray
    legs: STClothingLegsPantsGray
    shoes: ClothingShoesSwat


- type: job
  id: EvolverPackAlpha
  name: Альфа зграї
  icon: pack
  description: ватажок зграї, який контролює її дії та захищає її закони і порядок.
  playTimeTracker: JobEvolverPackAlpha
  requirements:
    - !type:RoleTimeRequirement
      role: JobEvolverPackAlpha
      time: 1
    - !type:SpeciesRequirement
      species:
      - Moth
      - Diona
      - Arachnid
      - Reptilian
      - SlimePerson
      - Vox
  startingGear: STEvolverPackAlphaGear
  supervisors: Підтримувати і зміцнювати владу в зграї, координуючи її напади і захист.
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Evolver
            - Pack
        - type: Bands
          band: Evolver
          bandIcon: pack
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: STEvolverPackAlphaGear
  equipment:
    id: BandPDA
    belt: ClothingBeltStorageWaistbag
    neck: ClothingNeckDogtagBrigand
    eyes: ClothingEyesGlassesSunglasses
    torso: STClothingTorsoJacketGray
    legs: STClothingLegsPantsGray
    shoes: ClothingShoesSwat
