- type: entity
  id: SpawnPointStalker
  parent: SpawnPointJobBase
  name: Stalker Job Spawn
  suffix: ST
  components:
    - type: SpawnPoint
      job_id: Stalker
    - type: Sprite
      layers:
        - state: green
        - state: security_officer

- type: entity
  id: SpawnPointSci
  parent: SpawnPointJobBase
  name: Scientist Job Spawn
  suffix: ST
  components:
    - type: SpawnPoint
      job_id: StalkerScientist
    - type: Sprite
      layers:
        - state: green
        - state: security_officer

- type: entity
  id: SpawnPointStalkerAnomalist
  parent: SpawnPointJobBase
  name: Anomalist Job Spawn
  suffix: ST
  components:
    - type: SpawnPoint
      job_id: StalkerAnomalist
    - type: Sprite
      layers:
        - state: green
        - state: security_officer

- type: entity
  id: SpawnPointBand
  parent: SpawnPointJobBase
  name: Bandit Job Spawn
  suffix: ST
  components:
    - type: SpawnPoint
      job_id: StalkerBandit
    - type: Sprite
      layers:
        - state: green
        - state: security_officer

- type: entity
  id: SpawnPointMilitary
  parent: SpawnPointJobBase
  name: Military Job Spawn
  suffix: ST
  components:
    - type: SpawnPoint
      job_id: Military
    - type: Sprite
      layers:
        - state: green
        - state: security_officer

- type: entity
  id: SpawnPointNeutral
  parent: SpawnPointJobBase
  name: Neutral Job Spawn
  suffix: ST
  components:
    - type: SpawnPoint
      job_id: StalkerNeutral
    - type: Sprite
      layers:
        - state: green
        - state: security_officer

- type: entity
  id: SpawnPointPoisk
  parent: SpawnPointJobBase
  name: Finding Job Spawn
  suffix: ST
  components:
    - type: SpawnPoint
      job_id: StalkerPoisk
    - type: Sprite
      layers:
        - state: green
        - state: security_officer
