- type: startingGear
  id: StalkerNewbieGearRuin
  equipment:
    id: StalkerPDA
    belt: ClothingBeltStorageWaistbag
    torso: ClothingTorsoSweaterStalkerGreen
    legs: ClothingLegsJeansStalker
    shoes: ClothingShoesBootsCombat
  storage:
    belt:
    - Roubles10