- type: entity
  parent: Clothing
  id: BaseClothingTorso
  suffix: ST, Торсо
  abstract: true
  components:
    - type: Sprite
      state: icon
    - type: Clothing
      slots:
        - TORSO
      equipSound:
        path: /Audio/Items/jumpsuit_equip.ogg
