- type: department
  id: Stalker
  name: Сталкерські ролі
  description: Ти справді це читаєш?
  weight: -500
  color: "#9FED55"
  roles:
  - StalkerTraderOld
  - StalkerStateOperative
  - LoneNewbie
  - ExperiencedLoner
  - LeaderLoner
  - BanditRookie
  - ExperienceBandit
  - PaxanBandit
  #- PrivateDuty
  #- SergantDuty
  #- GeneralDuty
  #- RookieFreedom
  #- ExperiencedFreedom
  #- LeaderFreedom
  - AdeptMonolit
  #- SoliderMonolit
  #- LeaderMonolit
  - RookieMercenary
  - ExperiencedMercenary
  - LeaderMercenary
  - PrivateMVC
  - SergantMVC
  - GeneralMVC
  - UnderCoverMilitary
  - RookieClearsky
  - ExperiencedClearsky
  - LeaderClearsky
  - ScienceAssistant
  - ScienceGroupLeader
