- type: entity
  parent:
    - BaseMob
    - MobDamageable
    - MobCombat
    - MobCharacteristics
    - MobWeight
    - MobLay
  id: STBaseMobMutated
  name: мутований
  description: Біжіть, якщо хочете жити!
  save: false
  abstract: true
  suffix: ST, ШІ, Мутований
  components:
    # AI
    - type: HTN
      rootTask:
        task: SimpleHostileCompound
    - type: NpcFactionMember
      factions:
        - Mutated
    - type: Climbing
    # Other
    - type: Tag
      tags:
        - FootstepSound
    - type: NoSlip
    - type: Reactive
      groups:
        Flammable: [Touch]
        Extinguish: [Touch]
        Acidic: [Touch, Ingestion]
    - type: MobMover
    - type: MovementSpeedModifier
      baseWalkSpeed: 2
      baseSprintSpeed: 3
    - type: HealthExaminable
      examinableTypes:
        - Blunt
        - Slash
        - Piercing
        - Heat
        - Shock
    - type: MovedByPressure
    - type: Fixtures
      fixtures:
        fix1:
          shape:
            !type:PhysShapeCircle
            radius: 0.35
          density: 250
          mask:
          - MobMask
          layer:
          - MobLayer
    - type: SolutionContainerManager
    - type: Bloodstream
      bloodMaxVolume: 100
      bloodlossDamage:
        types:
          Bloodloss:
            1
      bloodlossHealDamage:
        types:
          Bloodloss:
            -1
    - type: Damageable
      damageContainer: Biological
      damageModifierSet: DefaultMutant
    - type: AtmosExposed
    - type: Flammable
      fireSpread: true
      canResistFire: true
      damage:
        types:
          Heat: 1 #per second, scales with number of fire 'stacks'
    - type: Temperature
      heatDamageThreshold: 360
      coldDamageThreshold: 260
      currentTemperature: 310.15
      specificHeat: 42
      coldDamage:
        types:
          Cold : 0.1 #per second, scales with temperature & other constants
      heatDamage:
        types:
          Heat : 0.1 #per second, scales with temperature & other constants
    - type: MobState
    - type: MobThresholds
      thresholds:
        0: Alive
        50: Critical
        100: Dead
    - type: DamageStateVisuals
      states:
        Alive:
          Base: alive
        Critical:
          Base: critical
        Dead:
          Base: dead
    - type: Internals
    - type: StatusEffects
      allowed:
        - SlowedDown
        - Stutter
        - Electrocution
        - ForcedSleep
        - TemporaryBlindness
    - type: InjectableSolution
      solution: chemicals
    - type: Examiner
    - type: MeleeWeapon
      altDisarm: false
      hidden: true
      angle: 0
      animation: WeaponArcBite
      damage:
        groups:
          Brute: 5
    - type: Appearance
    - type: RotationVisuals
      defaultRotation: 0
      horizontalRotation: 0
    - type: FireVisuals
      sprite: Mobs/Effects/onfire.rsi
      normalState: Generic_mob_burning
    - type: Actions
    - type: DoAfter
    - type: Polymorphable
    - type: Pullable
    - type: Body
    - type: Buckle
    - type: StandingState
    - type: Alerts
    - type: SlowOnDamage
      speedModifierThresholds:
        60: 1
        80: 1
    - type: Perishable
    - type: Puller
      needsHands: false
    - type: Trash
      time: 900
