- type: job
  id: StalkerBandit
  name: Bandit
  icon: band
  description: Raiders and marauders of the Zone, ranging from small-time thugs and gangsters to organized crime syndicates.
  playTimeTracker: JobBandit
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobBandit
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: BandGear
  supervisors: Ви нікому не підкоряєтеся...
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Bandit
            - BanditHead
        - type: Bands
          band: Stalker
          bandIcon: band
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: job
  id: StalkerHeadBandit
  name: Pahan
  icon: band
  description: Raiders and marauders of the Zone, ranging from small-time thugs and gangsters to organized crime syndicates.
  playTimeTracker: JobHeadBandit
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobHeadBandit
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: BandGear
  supervisors: Ви нікому не підкоряєтеся...
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
          - Bandit
          - BanditHead
        - type: Bands
          band: Stalker
          bandIcon: band
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: BandGear
  equipment:
    id: BandPDA
    neck: ClothingBandageStalkerPetuh
    belt: ClothingBeltStorageWaistbag
    shoes: ClothingShoesBootsCombatFilled
    legs: ClothingLegsJeansBlue
    torso: ClothingTorsoJacketAdidas
