- type: job
  id: StalkerZapovit
  name: Заповіт
  icon: zapovit
  description: Це невелика армія надзвичайно небезпечних фанатиків.
  playTimeTracker: JobZapovit
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobZapovit
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: StalkerZapovitGear
  supervisors: Ви працюєте на Вищі Сили.
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        groups:
          - Covenant
        tags:
          - Covenant
          - Stalker
      - type: Bands
        band: Stalker
        bandIcon: zapovit
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3

- type: startingGear
  id: StalkerZapovitGear
  equipment:
    id: StalkerPDA
    belt: ClothingBeltStorageWaistbag
    torso: ClothingTorsoTurtlenecksCovenantHead
    legs: ClothingLegsJeansBlackCargo
    shoes: ClothingShoesBootsWork

- type: startingGear
  id: StalkerZapovitLeaderGear
  equipment:
    id: StalkerPDA
    belt: ClothingBeltStorageWaistbag
    torso: ClothingTorsoTurtlenecksCovenant
    legs: ClothingLegsJeansBrownCargo
    shoes: ClothingShoesBootsWork
