- type: job
  id: StalkerFreedom
  name: Freedom`s Fighter
  icon: freedom
  description: Zone Defender.
  playTimeTracker: JobFreedom
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobFreedom
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: FreedomGear
  supervisors: Кури, защищай Зону и игнорируй авторитеты.
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Freedom
        - type: Bands
          band: Stalker
          bandIcon: freedom
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: job
  id: StalkerHeadFreedom
  name: Ataman
  icon: freedom
  description: Zone Defender.
  playTimeTracker: JobHeadFreedom
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobHeadFreedom
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: FreedomGear
  supervisors: Командиры? У анархистов?.
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Freedom
            - FreedomHead
        - type: Bands
          band: Stalker
          bandIcon: freedom
        - type: BlockTackingHolyItems

- type: startingGear
  id: FreedomGear
  equipment:
    id: SvobodaPDA
    belt: ClothingBeltStorageWaistbag
    legs: ClothingLegsJeansFreedomCamouflage
    shoes: ClothingShoesBootsWork
    torso: ClothingTorsoTurtlenecksFreedomCamouflage
