- type: job
  id: StalkerMercenary
  name: PMC fighter Ion
  icon: merc
  description: Adventurers and thugs from all over the world.
  playTimeTracker: JobStalkerMercenary
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobStalkerMercenary
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: StalkerMercenaryGear
  supervisors: Вы чётко спланированная операция с отличной подготовкой — вот залог вашего успеха.
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Merc
            - Stalker
        - type: Bands
          altBand: stalker
          canChange: true
          band: Stalker
          bandIcon: merc
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: StalkerMercenaryGear
  equipment:
    id: BandPDA
    belt: ClothingBeltStorageWaistbag
    torso: STClothingTorsoJacketGray
    legs: STClothingLegsPantsGray
    shoes: ClothingShoesSwat


- type: job
  id: StalkerHeadMercenary
  name: PMC Officer Ion
  icon: merc
  description: Your responsibility is to maintain contact with headquarters and directly make decisions on the contract.
  playTimeTracker: JobStalkerHeadMercenary
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobStalkerHeadMercenary
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: StalkerHeadMercenaryGear
  supervisors: вы координируете тактические операции, обеспечиваете эффективное взаимодействие членов группировки и принимаете оперативные решения на поле боя
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - HeadMerc
            - Merc
            - Stalker
        - type: Bands
          altBand: stalker
          canChange: true
          band: Stalker
          bandIcon: merc
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: StalkerHeadMercenaryGear
  equipment:
    id: BandPDA
    belt: ClothingBeltStorageWaistbag
    neck: ClothingNeckDogtagBrigand
    eyes: ClothingEyesGlassesSunglasses
    torso: STClothingTorsoJacketGray
    legs: STClothingLegsPantsGray
    shoes: ClothingShoesSwat
