- type: job
  id: MilitaryStalker
  name: Військовий сталкер
  icon: voen
  description: Солдати, які пройшли спеціальну підготовку після досвіду служби в Зоні, або сталкери, які підписали контракт з армією.
  playTimeTracker: JobMilitaryStalker
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobMilitaryStalker
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: MilitarySpecGear
  supervisors: Ти будеш терпіти і страждати, Victoria cruenta
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        groups:
          - MilitaryStalker
      - type: Bands
        altBand: stalker
        canChange: true
        band: Stalker
        bandIcon: voen
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3

- type: job
  id: Military
  name: Військовий
  icon: army
  description: Утримувати зону для запобігання розкраданню небезпечних радіоактивних матеріалів і не допускати несанкціонованого проникнення туди будь-яких осіб.
  playTimeTracker: JobMilitary
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobMilitary
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: MilitaryGear
  supervisors: Ви підкоряєтеся старшим за званням.
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        groups:
          - Military
      - type: Bands
        band: Stalker
        bandIcon: army
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3


- type: job
  id: MilitaryHead
  name: Керівник військового відомства
  icon: army
  description: Утримувати зону для запобігання розкраданню небезпечних радіоактивних матеріалів і не допускати несанкціонованого проникнення туди будь-яких осіб.
  playTimeTracker: JobHeadMilitary
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobHeadMilitary
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: MilitaryGear
  supervisors: Ви підкоряєтеся старшим за званням.
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          groups:
            - MilitaryHead
        - type: Bands
          band: Stalker
          bandIcon: army
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: job
  id: MilitaryOfficer
  name: Військовий офіцер
  icon: army
  description: Утримувати зону для запобігання розкраданню небезпечних радіоактивних матеріалів і не допускати несанкціонованого проникнення туди будь-яких осіб.
  playTimeTracker: JobOfficerMilitary
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobOfficerMilitary
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: MilitaryGear
  supervisors: Ви підкоряєтеся старшим за званням.
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          groups:
            - MilitaryOfficer
        - type: Bands
          band: Stalker
          bandIcon: army
        - type: BlockTackingHolyItems

- type: startingGear
  id: MilitaryGear
  equipment:
    id: MilitaryPDA
    belt: ClothingBeltStorageWaistbag
    legs: ClothingLegsJeansGreenCargo
    torso: ClothingTorsoTurtlenecksMilitary
    shoes: ClothingShoesPortyanki
    head: STClothingHeadTinfoil

- type: startingGear
  id: MilitaryGearHead
  equipment:
    id: MilitaryPDA
    belt: ClothingBeltAssault
    legs: ClothingLegsJeansGreenCargo
    torso: ClothingTorsoTurtlenecksMilitary
    shoes: ClothingShoesPortyanki
    head: STClothingHeadTinfoil
    pocket1: STJobMilitaryIDCard

- type: startingGear
  id: MilitarySpecGear
  equipment:
    id: MilitaryPDA
    belt: ClothingBeltStorageWaistbag
    legs: ClothingLegsJeansGreenCargo
    torso: ClothingTorsoTurtlenecksMilitary
    shoes: ClothingShoesBootsCombatFilled

- type: startingGear
  id: OksopSpecOps
  equipment:
    id: MilitaryPDA
    belt: ClothingBeltMercWebbingStalker
    mask: ClothingMaskNeckBalaklava3
    back: ClothingBackpackDuffelCommonStalker
    legs: ClothingLegsJeansGreenCargo
    torso: ClothingTorsoTurtlenecksMilitary
    shoes: ClothingShoesBootsCombat
    outerarmor: STClothingOuterArmorLightPlateVestBaseHeavyMilitary
    pocket1: 739Mag75
    pocket2: 739Mag75
    suitstorage: STWeaponRifleStalkerAK103
