
- type: job
  id: StalkerNeutral
  name: Нейтрал
  icon: ne
  description: Захисники слабких
  playTimeTracker: JobNeutral
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobNeutral
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: NeutralGear
  supervisors: Ви підкоряєтеся своєму лідеру
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Neutral
            - Stalker
        - type: Bands
          band: Stalker
          bandIcon: ne
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: NeutralGear
  equipment:
    id: StalkerPDA
    belt: ClothingBeltStorageWaistbag
    torso: ClothingTorsoNeutral
    legs: ClothingLegsJeansNeutral
    shoes: ClothingShoesBootsCombatFilled
