
- type: job
  id: StalkerPoisk
  name: Search
  icon: poisk
  description: Search
  playTimeTracker: JobPoisk
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobPoisk
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: PoiskGear
  supervisors: Вы подчиняетесь своему лидеру
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Poisk
            - Stalker
        - type: Bands
          band: Stalker
          bandIcon: poisk
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: PoiskGear
  equipment:
    id: StalkerPDA
    belt: ClothingBeltStorageWaistbag
    torso: ClothingTorsoSweaterStalkerGreen
    legs: ClothingLegsJeansBlue
    shoes: ClothingShoesBootsCombatFilled
