- type: job
  id: Police
  name: policeman
  icon: police
  description: They are responsible for ensuring security and monitoring compliance with laws in the changing room.
  playTimeTracker: JobPolice
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobPolice
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: PoliceGear
  supervisors: Вы подчиняетесь старшим по званию.
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          groups:
            - PoliceOfficer
        - type: Bands
          band: Stalker
          bandIcon: police
        - type: BlockTackingHolyItems

- type: startingGear
  id: PoliceGear
  equipment:
    id: StalkerPDA
    torso: ClothingTorsoJacketPolice
    legs: ClothingLegsJeansPolice
    shoes: ClothingShoesBootsCombatFilled


