- type: entity
  parent: STBaseItem
  id: STBaseWeaponModule
  name: модуль лайна
  description: Хитромудрий пристрій для створення вундервафлі.
  abstract: true
  components:
    - type: STWeaponModule
    #  effect:
    #    fireRateModifier: 1
    #    angleDecayModifier: 1
    #    angleIncreaseModifier: 1
    #    maxAngleModifier: 1
    #    minAngleModifier: 1
    #    projectileSpeedModifier: 1
    #    soundGunshotVolumeAddition: 0
    - type: Sprite
      state: icon
