- type: entity
  parent: Clothing
  id: BaseClothingLegs
  suffix: Stalker, Ноги
  abstract: true
  components:
    - type: Sprite
      state: icon
    - type: Clothing
      slots:
        - LEGS
      equipSound:
        path: /Audio/Items/jumpsuit_equip.ogg
