- type: job
  id: MayorCity
  name: Мер
  icon: grajdansksprite
  description: Керує містом Чорнобиль-4. Він є центральним мозком міста.
  playTimeTracker: JobMayorCity
  requirements:
    - !type:RoleTimeRequirement
      role: JobMayorCity
      time: 1
  startingGear: MayorCityGear
  supervisors: Немає нікого головнішого за вас. Усі цивільні структури підпорядковуються вам.
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        tags:
          - MayorCity
          - Prokuror
          - Magistrate
          - Priest
          - Barthender
      - type: Bands
        band: Stalker
        bandIcon: grajdansksprite
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3


- type: job
  id: Prokuror
  name: Прокурор
  icon: grajdansksprite
  description: З'ясуйте правду, щоб представити її в суді.
  playTimeTracker: JobProkuror
  requirements:
    - !type:RoleTimeRequirement
      role: JobProkuror
      time: 1
  startingGear: ProkurorGear
  supervisors: Ви підпорядковуєтеся меру міста "Чорнобиль - 4".
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Prokuror
        - type: Bands
          band: Stalker
          bandIcon: grajdansksprite
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3


- type: job
  id: Magistrate
  name: Суддя
  icon: grajdansksprite
  description: Здійснювати правосуддя, орієнтуючись на закони міста Чорнобиль - 4.
  playTimeTracker: JobMagistrate
  requirements:
    - !type:RoleTimeRequirement
      role: JobMagistrate
      time: 1
  startingGear: MagistrateGear
  supervisors: Ви підпорядковуєтеся меру міста "Чорнобиль - 4".
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Magistrate
        - type: Bands
          band: Stalker
          bandIcon: grajdansksprite
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3


- type: job
  id: Priest
  name: Священик
  icon: grajdansksprite
  description: Допомагати людям у складних ситуаціях, навертаючи їх до релігії.
  playTimeTracker: JobPriest
  requirements:
    - !type:RoleTimeRequirement
      role: JobPriest
      time: 1
  startingGear: PriestGear
  supervisors: Ви підпорядковуєтеся меру міста "Чорнобиль - 4".
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Priest
        - type: Bands
          band: Stalker
          bandIcon: grajdansksprite
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3


- type: job
  id: StalkerBartender
  name: Бармен
  icon: grajdansksprite
  description: Працювати в барі, задовольняючи алкогольні потреби відвідувачів.
  playTimeTracker: JobStalkerBartender
  requirements:
    - !type:RoleTimeRequirement
      role: JobStalkerBartender
      time: 1
  startingGear: StalkerBartenderGear
  supervisors: Ви підпорядковуєтеся меру міста "Чорнобиль - 4".
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Barthender
        - type: Bands
          band: Stalker
          bandIcon: grajdansksprite
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3


- type: startingGear
  id: MayorCityGear
  equipment:
    id: StalkerPDA
    shoes: ClothingShoesBootsLeather
    legs: ClothingLegsJeansBlackCargo
    torso: ClothingTorsoSweaterStalkerGreen

- type: startingGear
  id: ProkurorGear
  equipment:
    id: StalkerPDA
    shoes: ClothingShoesBootsLeather
    legs: ClothingLegsJeansBlackCargo
    torso: ClothingTorsoSweaterStalkerGreen

- type: startingGear
  id: MagistrateGear
  equipment:
    id: StalkerPDA
    shoes: ClothingShoesBootsLeather
    legs: ClothingLegsJeansBlackCargo
    torso: ClothingTorsoSweaterStalkerGreen

- type: startingGear
  id: PriestGear
  equipment:
    id: StalkerPDA
    shoes: ClothingShoesBootsLeather
    legs: ClothingLegsJeansBlackCargo
    torso: ClothingTorsoSweaterStalkerGreen

- type: startingGear
  id: StalkerBartenderGear
  equipment:
    id: StalkerPDA
    shoes: ClothingShoesBootsLeather
    legs: ClothingLegsJeansBlackCargo
    torso: ClothingTorsoSweaterStalkerGreen
